build:
	cargo build --target wasm32-unknown-unknown --release
	./opt/binaryen-version_110/bin/wasm-opt --strip-debug target/wasm32-unknown-unknown/release/wasm.wasm -o target/wasm32-unknown-unknown/release/optimized.wasm

exec: build
	curl localhost:3000/v1/exec --data-binary @target/wasm32-unknown-unknown/release/optimized.wasm

size: build
	twiggy top -n 20 target/wasm32-unknown-unknown/release/optimized.wasm

show: build
	wasm2wat target/wasm32-unknown-unknown/release/optimized.wasm
